<a href="https://colab.research.google.com/github/davidmorme/Universidad/blob/main/Herramientas%20de%20Modelaci%C3%B3n/03_SistemasLineales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Systems : Matrices, Vectors, eigen systems
In this module we will learn how to solve linear systems which are very common in engineering.
Applications are numerous: 
- Civil, chemical, electrical, mechanical, ..., engineering
- In biology by using linear algebra to analyze huge data sets regarding protein folding. https://math.stackexchange.com/questions/571109/any-application-of-vector-spaces-in-biology-or-biotechnology
- In genetics to model the evolution of genes.
- Markov chains on industrial processes with applications of matrices and eigen systems. 
- Population dynamics. 
- Perception of colors. 
- Adjacency graphs: https://en.wikipedia.org/wiki/Adjacency_matrix , https://towardsdatascience.com/matrices-are-graphs-c9034f79cfd8

<img src="https://github.com/iluvatar1/ModelingToolsEngineering/blob/master/03-SistemasLineales-Matrices/fig/Linear-Systems-Applications.png?raw=1" width=900>

<img src="https://github.com/iluvatar1/ModelingToolsEngineering/blob/master/03-SistemasLineales-Matrices/fig/Matrices-rotations-eigenvalues.png?raw=1" width=900>


Ejemplos de rotaciones:
- https://www.glowscript.org/#/user/GlowScriptDemos/folder/Examples/program/Bounce-VPython
- https://www.glowscript.org/#/user/GlowScriptDemos/folder/Examples/program/Plot3D

<img src="https://github.com/iluvatar1/ModelingToolsEngineering/blob/master/03-SistemasLineales-Matrices/fig/bungee-family-equ.png?raw=1" width=900>

> Write this as a linear system $A\vec x = \vec b$, with unknows $x_1, x_2, x_3$



A = (k1+k2  -k2      0 
     -k2    k2+k3   -k3 
     0      -k3      k3) 
     
    [[k1 + k2, -k2  , 0  ],
     [-k2    , k2+k3, -k3],
     [0      , -k3  , k3]]

x = (x1
     x2
     x3)
     
b = (m1g
     m2g
     m3g)

# How to index a Matrix?
<img src="https://github.com/iluvatar1/ModelingToolsEngineering/blob/master/03-SistemasLineales-Matrices/fig/matrix-base.png?raw=1" width=900>

# Defining matrices in python

## Scipy
See https://docs.scipy.org/doc/numpy-1.17.0/reference/generated/numpy.array.html#numpy.array



In [ ]:
import numpy as np
A = np.array([[1, 2],  # primera fila, indice es 0
              [3, 4]]) # Segunda fila, indice es 1
print(A[0][1])
print(f"Matrix : \n", A)
#
A = np.array([1, 2, 3, 4]).reshape(2,2)
print("Matrix : \n", A)
print("A[1,0] : \n", A[1,0])
print("A[1][0] : \n", A[1][0])

2
Matrix : 
 [[1 2]
 [3 4]]
Matrix : 
 [[1 2]
 [3 4]]
A[1,0] : 
 3
A[1][0] : 
 3


# Matrix operations
Add, substract, multiply, etc


In [ ]:
import numpy as np
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, -1], [-3, 24]])
c = a+b # sum
print(c)
c = a*b # Multiplication
print(c)
c = a/b # divide element by element
print(c)
print(c.max())
print(c.min())
print(b/b)

[[ 6  1]
 [ 0 28]]
[[ 5 -2]
 [-9 96]]
[[ 0.2        -2.        ]
 [-1.          0.16666667]]
0.2
-2.0
[[1. 1.]
 [1. 1.]]


In [ ]:
import numpy as np
a = np.matrix([[1, 2],[3, 4]])
b = np.matrix([[5, -1], [-3, 24]])

c = a*b # Multiplication
print(c)

[[-1 47]
 [ 3 93]]


# Solving linear systems $A\vec x= \vec b$
Solve the following system:
<img src="https://github.com/iluvatar1/ModelingToolsEngineering/blob/master/03-SistemasLineales-Matrices/fig/linear-example-01.png?raw=1" width=600>

In [ ]:
import numpy as np

A = np.array([[150, -100, 0], 
              [-100, 150, -50], 
              [0, -50, 50]])
b = np.array([588.6, 686.7, 784.8])
x = np.linalg.solve(A, b) # magic
print("Solution: \n", x)
# confirm
print("Delta:\n", A.dot(x) - b)

Solution: 
 [41.202 55.917 71.613]
Delta:
 [-1.13686838e-13  1.25055521e-12  1.13686838e-13]


In [ ]:
import numpy as np

N = 1000

A = np.random.rand(N,N)
b = np.random.rand(N)
x = np.linalg.solve(A, b) # magic
#print("Solution: \n", x)
# confirm
#print("Delta:\n", A.dot(x) - b)

## Exercise: Rewrite and solve the following system

<img src="https://github.com/iluvatar1/ModelingToolsEngineering/blob/master/03-SistemasLineales-Matrices/fig/linear-example-03.png?raw=1" width=600>

In [ ]:
import numpy as np

A = np.array([[0, -6 , 5], 
              [0, 2, 7], 
              [-4, 3, -7]])
b = np.array([50, -30, 50])
x = np.linalg.solve(A, b) # magic
print("Solution: \n", x)
# confirm
print("Delta:\n", A.dot(x) - b)

Solution: 
 [-17.01923077  -9.61538462  -1.53846154]
Delta:
 [0. 0. 0.]


## Exercise: Rewrite and solve the following system
Extra: Can yu measure the time spent in the computation? (google for timer or timeit in python)

<img src="https://github.com/iluvatar1/ModelingToolsEngineering/blob/master/03-SistemasLineales-Matrices/fig/linear-example-02.png?raw=1" width=600>

In [ ]:
import numpy as np

A = np.array([[1,1,1,0,0,0], 
              [0,-1,0,1,-1,0], 
              [0,0,-1,0,0,1], 
              [0,0,0,0,1,-1], 
              [0,10,-11,0,-15,-5], 
              [5,-10,0,-20,0,0]])
b = np.array([0,0,0,0,0,200])
x = np.linalg.solve(A, b) # magic
print("Solution: \n", x)
# confirm
print("Delta:\n", A.dot(x) - b)

Solution: 
 [ 6.1423221  -4.64419476 -1.49812734 -6.1423221  -1.49812734 -1.49812734]
Delta:
 [ 2.66453526e-15 -2.22044605e-16 -2.22044605e-16  0.00000000e+00
  0.00000000e+00  0.00000000e+00]


## Exercise: Solve and plot the following system

$$ \frac{-2.3x_1}{5} + x_2 = 1.1 $$
$$-0.5x_1 + x_2 = 1 $$
Plot the system of equations and check whether this solution is or
not special.


In [ ]:
import numpy as np

A = np.array([[-2.3/5 , 1], 
              [-0.5, 1]])
b = np.array([1.1, 1])
x = np.linalg.solve(A, b) # magic
print("Solution: \n", x)
# confirm
print("Delta:\n", A.dot(x) - b)

Solution: 
 [2.5  2.25]
Delta:
 [0. 0.]


## Exercise: Simulating temperature
|Temperature| System of equations|
|-|-|
|<img src="https://github.com/iluvatar1/ModelingToolsEngineering/blob/master/03-SistemasLineales-Matrices/fig/linear-example-04-T.png?raw=1" width=800>| <img src="https://github.com/iluvatar1/ModelingToolsEngineering/blob/master/03-SistemasLineales-Matrices/fig/linear-example-04-T-B.png?raw=1" width=800>|

# Computing inverse matrices
See : https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.inv.html#scipy.linalg.inv

You can watch: https://www.youtube.com/watch?v=uQhTuRlWMxw



In [ ]:
%time
from scipy import linalg
import numpy as np
A = np.array([[1., 2.], 
              [3., 4.]])
B = linalg.inv(A) # magic
print("B : \n", B)
# verify
print("A A^-1 : \n", A.dot(B))

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 8.34 µs
B : 
 [[-2.   1. ]
 [ 1.5 -0.5]]
A A^-1 : 
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [ ]:
linalg.norm(A)*linalg.norm(B)

14.999999999999998

In [ ]:
from scipy import linalg
import numpy as np
N = 100
A = np.random.rand(N, N)
B = linalg.inv(A) # magic
print("B : \n", B)
# verify
print("A A^-1 : \n", A.dot(B))

B : 
 [[ 0.11332073 -0.49662963  0.01710919 ... -0.452055    0.60237026
   0.22189291]
 [-0.28169594  0.62099745 -0.26101717 ...  0.24471722 -0.46723112
  -0.62285853]
 [-0.00873061 -0.00367196  0.18976762 ... -0.33323377  0.39416792
   0.13367438]
 ...
 [ 0.01538868 -0.09082214  0.03788307 ... -0.12650046  0.17662537
   0.3067401 ]
 [-0.00937432  0.04538702  0.03561379 ...  0.20821335 -0.08121583
   0.02131982]
 [-0.0652248   0.37259089  0.02297382 ...  0.31741976 -0.40911639
  -0.17294218]]
A A^-1 : 
 [[ 1.00000000e+00  5.05911069e-15  1.39911924e-15 ...  1.57012781e-15
  -8.87591487e-16 -1.23335621e-15]
 [ 1.15534196e-16  1.00000000e+00 -1.64862681e-16 ...  3.11933814e-15
   5.96883545e-17 -1.34368560e-15]
 [ 4.52785689e-17  6.78769392e-15  1.00000000e+00 ...  4.02900260e-15
  -1.90689951e-15 -1.84802840e-15]
 ...
 [ 8.85873805e-16  6.28442476e-15  3.42165247e-16 ...  1.00000000e+00
  -2.92420039e-15 -2.89944931e-15]
 [ 2.55439302e-16  6.72142666e-15  1.34262737e-15 ...  1.08140492e

In [ ]:
linalg.norm(A)*linalg.norm(B)

2278.5163032234796

## The condition number
The number
$$\kappa = ||A|| ||A^{-1}||$$
is called the condition number of a matrix. Ideally it is $1$. If $\kappa$ is much
larger than one, the matrix is ill-conditioned and the solution
might have a lot of error.
> Compute the condition number of the following matrix:
   \begin{equation}
   A = 
   \begin{bmatrix}
   1.001 & 0.001\\
   0.000 & 0.999
   \end{bmatrix}
   \end{equation}
Plot the associate system to check for the result


In [ ]:
from scipy import linalg
import numpy as np
A = np.array([[1.001, 0.001],
                [0.000, 0.999]])
kappa = linalg.norm(A)*linalg.norm(linalg.inv(A))
print(f"{kappa = }")

# Eigen values and eigen vectors
The eigen-values ${\lambda_i}$ and eigen-vectors ${x}$ of a matrix satisfy the equation 

$$ A\vec x = \lambda \vec x $$

The eigen-vectors form a basis where the matrix can be
diagonalized. In general, computing the eigen vectors and
aeigenvalues is hard, and they can also be complex.

For a more visual introduction watch:  https://www.youtube.com/watch?v=PFDu9oVAE-g

<img src="https://github.com/iluvatar1/ModelingToolsEngineering/blob/master/03-SistemasLineales-Matrices/fig/vector-field.png?raw=1" width=700>
REF: https://www.reddit.com/r/math/comments/b7ou6t/3blue1brown_overview_of_differential_equations/

In [ ]:
# See : https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.eig.html#scipy.linalg.eig
import numpy as np
from scipy import linalg
#A = np.array([[0., -1.], [1., 0.]])
#A = np.array([[1, 0.], [0., 2.]])
A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
sol = linalg.eig(A) # magic
print("Eigen-values: ", sol[0])
print("Eigen-vectors:\n", sol[1])
# verify
print("Verification: ", A.dot(sol[1][:, 0]) - sol[0][0]*sol[1][:, 0])


## Exercise
Find the eigen-values and eigen-vectors for the following system
<img src="https://github.com/iluvatar1/ModelingToolsEngineering/blob/master/03-SistemasLineales-Matrices/fig/eigen-exer-02.png?raw=1" width=700>

In [ ]:
import numpy as np
from scipy import linalg
A = np.array([[5, 4, 1, 1], 
              [4, 5, 1, 1], 
              [1, 1, 4, 2], 
              [1, 1, 2, 4]])
sol = linalg.eig(A) # magic
print("Eigen-values: ", sol[0])
print("Eigen-vectors:\n", sol[1])
# verify
print("Verification: ", A.dot(sol[1][:, 0]) - sol[0][0]*sol[1][:, 0])


# Problems

<img src="https://github.com/iluvatar1/ModelingToolsEngineering/blob/master/03-SistemasLineales-Matrices/fig/problem-03.png?raw=1" width=700>

Let $\vec x = (a, b)$ be a two-dimensional vector. Write a matrix that rotates the vector by 90 degrees. Use matrix multiplication to check your results. 

|System | Model |
|-|-|
|<img src="https://github.com/iluvatar1/ModelingToolsEngineering/blob/master/03-SistemasLineales-Matrices/fig/problem-04-B.png?raw=1" width=700>|<img src="https://github.com/iluvatar1/ModelingToolsEngineering/blob/master/03-SistemasLineales-Matrices/fig/problem-04.png?raw=1" width=700>|

In [ ]:
# Equations
# Q01c01 + Q31c3 = Q15c1 + Q12c1 ---> (Q15 + Q12)c1 - Q31c3           = Q01c01
# Q12c1 = Q25c2 + Q24c2 + Q23c2  ---> Q12c1 - (Q25 + Q24 + Q23) c2    = 0
# Q23c2 + Q03c03 = Q31c3 + Q34c3 ---> Q23c2 - (Q31 + Q34)c3           = -Q03c03
# Q24c2 + Q34c3 + Q54c5 = Q44c4  ---> Q24c2 + Q34c3 - Q44c4 + Q54c5 = 0
# Q15c1 + Q25c2 = Q54c5 + Q55c5  ---> Q15c1 + Q25c2 - (Q54 + Q55)c5   = 0

Q01 = 6; Q03 = 7
Q12 = 4; Q15 = 5
Q23 = 2; Q24 = 1; Q25 = 1
Q31 = 3; Q34 = 6
Q44 = 9
Q54 = 2; Q55 = 4
c01 = 20; c03 = 50

from scipy import linalg
import numpy as np
A = np.array([[(Q15 + Q12), 0, - Q31, 0, 0],
              [Q12, -(Q25 + Q24 + Q23), 0, 0, 0],
              [0, Q23, -(Q31 + Q34), 0, 0],
              [0, Q24, Q34, - Q44, Q54],
              [Q15, Q25, 0, 0, -(Q54 + Q55)]])
b = np.array([Q01*c01, 0, -Q03*c03, 0, 0])
c = linalg.solve(A, b)
print(c)
# Check
print(A.dot(c) - b)

<img src="https://github.com/iluvatar1/ModelingToolsEngineering/blob/master/03-SistemasLineales-Matrices/fig/problem-05.png?raw=1" width=700>

<img src="https://github.com/iluvatar1/ModelingToolsEngineering/blob/master/03-SistemasLineales-Matrices/fig/problem-06.png?raw=1" width=700>

| Statement | Table|
|-|-|
|<img src="https://github.com/iluvatar1/ModelingToolsEngineering/blob/master/03-SistemasLineales-Matrices/fig/problem-07-A.png?raw=1" width=500> | <img src="https://github.com/iluvatar1/ModelingToolsEngineering/blob/master/03-SistemasLineales-Matrices/fig/problem-07-B.png?raw=1" width=500>|

<img src="https://github.com/iluvatar1/ModelingToolsEngineering/blob/master/03-SistemasLineales-Matrices/fig/problem-08.png?raw=1" width=700>