<a href="https://colab.research.google.com/github/davidmorme/Universidad/blob/main/Data%20Camp/Introducci%C3%B3n_a_Phyton.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
baseball=pd.read_csv("/content/drive/My Drive/baseball.csv")
soccer=pd.read_csv("/content/drive/My Drive/soccer.csv")

In [ ]:
import numpy as np
x=np.array([1,2,3,4,5,6])
print(x[3:5])

[4 5]


In [ ]:
import numpy as np
x=np.array([1,2,3,4,5,6])
print(max(x))

6


In [ ]:
#Imprimir datos de una matriz
import numpy as np
x=np.array([[1,2,3,4,5,6],
            [5,9,8,7,6,5]])
print(x[1,2])

8


In [ ]:
#Borrar datos de una lista de objetos
import numpy as np
x=[1,2,3,4,5,6]
del(x[3:5])
print(x)

[1, 2, 3, 6]


In [ ]:
x=0
y=1
z=2
print([x,y,z])
print(x,y,z)

[0, 1, 2]
0 1 2


In [ ]:
# "%" es módulo, "/" es división
print(1/4)
print(7%4)

0.25
3


In [ ]:
# contar veces que se repite un dato en una lista
x=[2,5,"G","g","A",5,5,"A"]
print(x.count("A"))
print(x.count("g"))
print(x.count(5))

2
1
3


In [ ]:
#Imprimir datos de una lista matricial
x=[[2,5,"G","g","A",5,5,"A"],[1,2,3,4,5,6,7,8],["F","e",9,13,634,54,3,"t"]]
print(x[2][0:4])
print(x[0:2])

['F', 'e', 9, 13]
[[2, 5, 'G', 'g', 'A', 5, 5, 'A'], [1, 2, 3, 4, 5, 6, 7, 8]]


In [ ]:
x=[1,2,3,4,5,6,7,8,9,0,1,1,42534,653,2,3,542,567,54]
y=x
del(y[2])
print(x);print(y)


[1, 2, 4, 5, 6, 7, 8, 9, 0, 1, 1, 42534, 653, 2, 3, 542, 567, 54]
[1, 2, 4, 5, 6, 7, 8, 9, 0, 1, 1, 42534, 653, 2, 3, 542, 567, 54]


In [ ]:
x=[1,2,3,4,5,6,7,8,9,0,1,1,42534,653,2,3,542,567,54]
y=list(x)
del(y[2])
print(x);print(y)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 1, 42534, 653, 2, 3, 542, 567, 54]
[1, 2, 4, 5, 6, 7, 8, 9, 0, 1, 1, 42534, 653, 2, 3, 542, 567, 54]


In [ ]:
help(round)

Help on built-in function round in module builtins:

round(...)
    round(number[, ndigits]) -> number
    
    Round a number to a given precision in decimal digits (default 0 digits).
    This returns an int when called with one argument, otherwise the
    same type as the number. ndigits may be negative.



In [ ]:
#Número complejo
complex(35,5)

(35+5j)

In [ ]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full=first+second

# Sort full in descending order: full_sorted
full_sorted=sorted(full,reverse=True)
# Si reverse es False, la lista va a estar en orden ascendente. Si reverse es reverse es True, es en orden descendente
# Print out full_sorted
print(full_sorted)

In [ ]:
# string to experiment with: place
place = "poolhouse"

# Use upper() on place: place_up
place_up=place.capitalize()

# Print out place and place_up
print(place, place_up)

# Print out the number of o's in place
print(place.count("o"))

poolhouse Poolhouse
3


In [ ]:
# string to experiment with: place
place = "poolhouse"

# Use upper() on place: place_up
place_up=place.upper()

# Print out place and place_up
print(place, place_up)

# Print out the number of o's in place
print(place.count("o"))

poolhouse POOLHOUSE
3


In [ ]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20.0))

# Print out how often 9.50 appears in areas
print(areas.count(9.50))

In [ ]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size
areas.append(24.5)
areas.append(15.45)

# Print out areas
print(areas)

# Reverse the orders of the elements in areas
areas.reverse()

# Print out areas
print(areas)

In [ ]:
# Definition of radius
r = 0.43

# Import the math package
import math

# Calculate C
C = 2*math.pi*r

# Calculate A
A = math.pi*r**2

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

In [ ]:
# Definition of radius
r = 192500

# Import radians function of math package
from math import radians

# Travel distance of Moon over 12 degrees. Store in dist.
dist=r*radians(12)

# Print out dist
print(dist)

In [ ]:
# Inversa de una matriz
from scipy.linalg import inv as my_inv
import numpy as np
org=np.matrix([[1,2], [3,4]])
inv=np.matrix(my_inv(org))

print(org)
print(inv)
print(org*inv)
print(inv*org)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
[[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]


In [ ]:
# Inversa de una matriz
from scipy.linalg import inv as my_inv
import numpy as np
org=np.matrix([[2,3,4],[4,3,2],[0,1,0]])
inv=np.matrix(my_inv(org))
print(org)
print(inv)
print(org*inv)
print(inv*org)

[[2 3 4]
 [4 3 2]
 [0 1 0]]
[[-0.16666667  0.33333333 -0.5       ]
 [ 0.          0.          1.        ]
 [ 0.33333333 -0.16666667 -0.5       ]]
[[ 1.00000000e+00  1.11022302e-16  0.00000000e+00]
 [-1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[1.00000000e+00 1.11022302e-16 0.00000000e+00]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]


In [ ]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball=np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

In [ ]:
# height is available as a regular list

# Import numpy
import numpy as np

# Create a numpy array from height_in: np_height_in
np_height_in=np.array(height_in)

# Print out np_height_in
print(np_height_in)

# Convert np_height_in to m: np_height_m
np_height_m=0.0254*np_height_in

# Print np_height_m
print(np_height_m)

In [ ]:
# height and weight are available as regular lists

# Import numpy
import numpy as np

# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Create array from weight_lb with metric units: np_weight_kg
np_weight_kg=0.453592*np.array(weight_lb)

# Calculate the BMI: bmi
bmi=np_weight_kg/np_height_m**2

# Print out bmi
print(bmi)

In [ ]:
# height and weight are available as a regular lists

# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height_in) * 0.0254
np_weight_kg = np.array(weight_lb) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light=bmi<21

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])

In [ ]:
# height and weight are available as a regular lists

# Import numpy
import numpy as np

# Store weight and height lists as numpy arrays
np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

# Print out the weight at index 50
print(np_weight_lb[50])

# Print out sub-array of np_height_in: index 100 up to and including index 110
print(np_height_in[100:111])

In [ ]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball=np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

In [ ]:
# baseball is available as a regular list of lists

# Import numpy package
import numpy as np

# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 50th row of np_baseball
print(np_baseball[49])

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb=np_baseball[:,1]

# Print out height of 124th player
print(np_baseball[123][0])

In [ ]:
# baseball is available as a regular list of lists
# updated is available as 2D numpy array

# Import numpy package
import numpy as np

# Create np_baseball (3 cols)
np_baseball = np.array(baseball)

# Print out addition of np_baseball and updated
print(np_baseball+updated)

# Create numpy array: conversion
conversion=np.array([0.0254,0.453592,1])

# Print out product of np_baseball and conversion
print(np_baseball*conversion)

In [ ]:
# Create baseball, a list of lists
baseball = np.array([[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]])
print(baseball[:][0])
print(baseball[:,0])

[180.   78.4]
[180. 215. 210. 188.]


In [ ]:
# np_baseball is available

# Import numpy
import numpy as np

# Create np_height_in from np_baseball
np_height_in=np_baseball[:,0]

# Print out the mean of np_height_in
print(np.mean(np_height_in))

# Print out the median of np_height_in
print(np.median(np_height_in))

In [ ]:
# np_baseball is available

# Import numpy
import numpy as np

# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0],np_baseball[:,1])
print("Correlation: " + str(corr))

In [ ]:
# heights and positions are available as lists

# Import numpy
import numpy as np

# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions=np.array(positions)
np_heights=np.array(heights)

# Heights of the goalkeepers: gk_heights
gk_heights=np_heights[np_positions=="GK"]

# Heights of the other players: other_heights
other_heights=np_heights[np_positions!="GK"]

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

In [ ]:
help(x.index)

Help on built-in function index:

index(...) method of builtins.list instance
    L.index(value, [start, [stop]]) -> integer -- return first index of value.
    Raises ValueError if the value is not present.

